"""
Polymarket Wallet Setup Script
- Approves required contracts for trading
- Generates CLOB API credentials
- Saves everything to .env.bot

Run: python deploy_wallet.py
"""

import os
import sys
import getpass
from pathlib import Path

try:
    from py_clob_client.client import ClobClient
    from py_clob_client.clob_types import ApiCreds
    from py_clob_client.constants import POLYGON
except ImportError:
    print("[ERROR] py_clob_client not installed!")
    print("Run: pip install py-clob-client")
    sys.exit(1)

try:
    from eth_account import Account
except ImportError:
    print("[ERROR] eth-account not installed!")
    print("Run: pip install eth-account")
    sys.exit(1)


CLOB_HOST = "https://clob.polymarket.com"
CHAIN_ID = POLYGON  # 137 = Polygon mainnet


def main():
    print("\n" + "=" * 50)
    print("  POLYMARKET WALLET SETUP")
    print("  Deploy & approve contracts for bot trading")
    print("=" * 50 + "\n")

    # Get private key securely (hidden input)
    print("[INPUT] Paste your wallet PRIVATE KEY below.")
    print("        (Input is hidden - won't show on screen)\n")
    
    private_key = getpass.getpass("Private Key (0x...): ").strip()
    
    if not private_key:
        print("[ERROR] No private key provided!")
        sys.exit(1)
    
    # Add 0x prefix if missing
    if not private_key.startswith("0x"):
        private_key = "0x" + private_key

    # Validate key
    try:
        account = Account.from_key(private_key)
        address = account.address
        print(f"\n[OK] Wallet address: {address}")
    except Exception as e:
        print(f"[ERROR] Invalid private key: {e}")
        sys.exit(1)

    # Step 1: Initialize CLOB client
    print("\n[1/4] Connecting to Polymarket CLOB...")
    try:
        client = ClobClient(
            host=CLOB_HOST,
            chain_id=CHAIN_ID,
            key=private_key,
        )
        print("[OK] Connected to Polymarket CLOB")
    except Exception as e:
        print(f"[ERROR] Connection failed: {e}")
        sys.exit(1)

    # Step 2: Derive API credentials
    print("\n[2/4] Generating API credentials...")
    try:
        api_creds = client.derive_api_key()
        print(f"[OK] API Key: {api_creds.api_key[:10]}...")
        print(f"[OK] Secret: {api_creds.api_secret[:10]}...")
        print(f"[OK] Passphrase: {api_creds.api_passphrase[:10]}...")
    except Exception as e:
        print(f"[ERROR] Failed to derive API key: {e}")
        print("\n[INFO] This might mean:")
        print("  - Your wallet has no POL for gas")
        print("  - Network is congested, try again later")
        print("  - Wallet needs to be registered on Polymarket first")
        print("\n[TIP] Try visiting polymarket.com and connecting this wallet first.")
        sys.exit(1)

    # Step 3: Set allowances (approve contracts)
    print("\n[3/4] Approving Polymarket contracts...")
    try:
        # This approves CTF Exchange, Neg Risk CTF Exchange, Neg Risk Adapter
        client.set_allowances()
        print("[OK] All contracts approved!")
    except Exception as e:
        print(f"[WARN] Approval may have failed: {e}")
        print("[INFO] You might need more POL for gas. Continuing anyway...")

    # Step 4: Get proxy/safe wallet address
    print("\n[4/4] Getting Polymarket proxy wallet address...")
    proxy_address = address  # Default to same address
    try:
        # Try to get the proxy wallet
        proxy_address = client.get_address()
        if proxy_address:
            print(f"[OK] Proxy/Safe address: {proxy_address}")
        else:
            proxy_address = address
            print(f"[INFO] No proxy found, using main address: {address}")
    except Exception:
        print(f"[INFO] Using main wallet address: {address}")

    # Save to .env.bot
    print("\n[SAVE] Writing credentials to .env.bot...")
    
    env_content = f"""# ============================================
# POLYMARKET BTC UP/DOWN TRADING BOT CONFIG
# Generated by deploy_wallet.py
# ============================================

# --- TRADING MODE ---
DRY_RUN=false
BANKROLL=2.00

# --- STRATEGY PARAMETERS ---
MIN_EDGE=0.05
MIN_PROB=0.87
MIN_BET=0.25
MAX_BET=1.00
LOOP_INTERVAL=81

# --- POLYMARKET WALLET ---
PRIVATE_KEY={private_key}
SAFE_ADDRESS={proxy_address}

# --- API CREDENTIALS ---
CLOB_API_KEY={api_creds.api_key}
CLOB_API_SECRET={api_creds.api_secret}
CLOB_API_PASSPHRASE={api_creds.api_passphrase}

# --- TELEGRAM (optional) ---
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
"""

    env_path = Path(__file__).parent / ".env.bot"
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"[OK] Saved to: {env_path}")

    # Summary
    print("\n" + "=" * 50)
    print("  SETUP COMPLETE!")
    print("=" * 50)
    print(f"\n  Wallet:  {address}")
    print(f"  Proxy:   {proxy_address}")
    print(f"  API Key: {api_creds.api_key[:10]}...")
    print(f"  Mode:    LIVE (DRY_RUN=false)")
    print(f"  Bankroll: $2.00")
    print(f"\n  Next: Run the bot with: .\\run.ps1")
    print(f"\n  WARNING: Start with DRY_RUN=true first to validate!")
    print(f"  Edit .env.bot → set DRY_RUN=true for safe testing")
    print("=" * 50 + "\n")


if __name__ == "__main__":
    main()
